### PR TITLE
Fix text indentation issues when setting a paragraph style

### PR DESCRIPTION
**Pull request by jeffaburt**
Props to @kwketh for finding the solution to this. This fixes issues #705, #693 and #607, and possibly #644 and #511.

In my case, I wanted to left align the text on each line, independent of the bullet character.

My paragraph style looks something like the following:

```
let paragrahStyle = NSMutableParagraphStyle()
paragrahStyle.paragraphSpacing = 4
paragrahStyle.paragraphSpacingBefore = 3
paragrahStyle.firstLineHeadIndent = 0
paragrahStyle.headIndent = label.font.pointSize / 1.75
```

***Without the changes in this PR, the text is not left aligned:***
image

***After the changes in this PR, the indentation works properly again:***
image

### CODE REVIEW

**Comment by segiddins** [comment]
Could you add test coverage for this change?

**Comment by BobDG** [comment]
Anyone working on this? The solution works perfectly for me :)

**Comment by eliasisrael** [comment]
Anyone? Looks like this fix fell by the wayside.

**Comment by ugiacoman** [comment]
Running into this issue now, is there a reason this wasn't merged back in the day?

**Pull request closed without merging**
