### PR TITLE
[Links] Block-based link tap and long press handling

### LINKED ISSUE #490: Improvement: addLinkToTarget:action:withRange:
It would be very nice to have a method like 

```
      - (void)addLinkToTarget:(id)target action:(SEL)selector withRange:(NSRange)range
```

### PR DESCRIPTION
**Pull request by jhersh**
Fixes #490.

### CODE REVIEW

**Comment by getaaron** [comment]
:+1:

**Comment by getaaron** [comment]
What's up with the duplicate Coveralls comments?

**Comment by jhersh** [comment]
I squashed and pushed a few times. Sorry!

**Comment by getaaron** [comment]
Ah got it. No worries, just curious :)

**Comment by tamastimar** [comment]
Hello! I was searching for exactly this feature. Do you have any ETA for a release? Thanks.

**Comment by jhersh** [comment]
@tamastimar TTTAttributedLabel [`1.13.3`](https://github.com/TTTAttributedLabel/TTTAttributedLabel/releases/tag/1.13.3) is now available!

**Pull request merged**
