### PR TITLE
[IBDesignable] Opt-out designable and inspectable

### LINKED ISSUE #460: Usage in IB gives error messages but app works
Hi,
I tried to use this library/component for its link-ability.
I added it as a Pod. This works without problems.

One of my projects needs to have touchable words in a UILabel. The view hosting this UILabel is designed in a xib.

I tried to set the Class of the UILabel to TTTAttributedLabel, because it seems to support IB_DESIGNABLE and the respective Inspectables.

The Inspectable attributes appear in the attributes inspector and the app compiles and runs fine.

I just have nasty error message which I dont quiet get:

screen shot 2014-11-21 at 12 37 54
screen shot 2014-11-21 at 12 38 35

They seem just to be about the component to fail being renderable inside Interface Builder. If thats the case, how to disable these errors? If its more than that I would appreciate help to get rid of them.

Thanks in advance.

### PR DESCRIPTION
**Pull request by jhersh**
Fixes #460, #510, #520.

### CODE REVIEW

**Comment by jhersh** [comment]
I don't really like this. Also it is not clear if, when imported as a static library via CocoaPods, you can reliably inject a preprocessor define (`TTT_NO_DESIGNABLE`) before the pod is compiled.

**Comment by jhersh** [comment]
We could define a `TTTAttributedLabel` subspec that added a preprocessor define, but it would require those users to switch to that subspec.

**Comment by cashmash** [comment]
will that be merged?

**Comment by jhersh** [comment]
@cashmash probably not in this current form; it is problematic especially when used with CocoaPods. I would welcome suggestions here :)

**Comment by Fl0p** [comment]
@jhersh you can create additional podspec version only for this fix
something like
```JSON
  "name": "TTTAttributedLabel",
  "version": "1.13.NO_DESIGNABLE",
```
pointed on this commit 
```JSON
  "source": {
    "git": "https://github.com/TTTAttributedLabel/TTTAttributedLabel.git",
    "commit": "7e62171a114768725dbf99e10cee83f15f3c98e0"
  },
```
also with preprocessor flag
```JSON
"xcconfig": {
    "GCC_PREPROCESSOR_DEFINITIONS": "$(inherited) TTT_NO_DESIGNABLE=1"
  },
```

so enduser just need to install version without designable like this
```rb
pod 'TTTAttributedLabel', '1.13.NO_DESIGNABLE'
```

**Comment by jhersh** [comment]
That would require us to maintain two releases in parallel, indefinitely, which is really not sustainable. I don't really like the subspec idea for a similar reason -- it would require everyone to switch. Other suggestions are welcome here.

**Comment by Fl0p** [comment]
@jhersh 
Why maintain ?
Just deprecate it and move forward.  IOS9 is coming.
Everybody will use next OS versions with Dynamic Framework linking and swift 2.0

Only few retrogrades will support IOS 3.1.1
And there are version them - 1.13.NO_DESIGNABLE 
Until they update theirs project to brand new awesome technologies.
If they want more they always can fork and use theirs own fork and commit.

**Comment by jhersh** [comment]
One of the hallmark features of this project has been backwards compatibility to iOS 4.3. It's true that won't be maintainable forever but I think we should not be so quick to dismiss it :)

**Comment by Fl0p** [comment]
Ho Ho Ho 
Here the solution that will do everything automatically

- You need a custom script (bash, ruby or other) 
 - this script should scan ../podfile to !use_frameworks keyword
 - if found it should use Xcodeproj to add TTT_NO_DESIGNABLE=1 macro to Pods-TTTAttributedLabel target
- than add this script to prepare_command of your spec.

@jhersh thoughts ?

**Comment by hagile** [comment]
@Fl0p I'm agree with your thoughts. iOS 9 has been already launched by Apple and now its time to update this awesome library for iOS 7 and greater, send all deprecated methods to the hell. Except few companies who're still supporting iOS 3.1. is just too much as there are not enough devices running this version of iOS. @jhersh, you should really mind our comments and do some hallmark changes in this. Where's the @mattt, please share your thoughts as well? If one want to support prior versions they can definitely fork it and use it. For that particular reason, we can't miss super awesome features of new iOS. Waiting for great update on this.

**Comment by jhersh** [comment]
There is nothing proposed in this change that requires increasing the minimum deployment target or dropping older iOS SDKs. How is that relevant here?

The specific item under discussion here is a mechanism that allows the developer to enable or disable `TTTAttributedLabel`'s IB annotations. Enabling or disabling these annotations must be a conscious decision that the developer makes for each of her projects; @Fl0p's script idea, while interesting, takes that choice away from the developer and is too much 'magic' that will be confusing or unclear to the developer.

We are essentially talking about a compile-time switch using one of these mechanisms:

1.  Add a `#define` to your project that changes behavior of the label. This is what is currently implemented here in this PR, but it is problematic in CocoaPods to ensure the define is set before the Pods project is compiled
2. Add a new `TTTAttributedLabel` subspec, perhaps something like `TTTAttributedLabel/NoDesignable`, that lets you easily switch in your Podfile between these two configurations
3. Sidestep the problem entirely by installing `TTTAttributedLabel` as either a dynamic framework or by dragging the files to your project

I am leaning towards `2`. Thoughts?

**Comment by jhersh** [comment]
Added subspecs as per `2` above. I think this is a workable option.

**Comment by getaaron** [comment]
@jhersh I think that's the least objectionable proposal I've seen. Pretty cool - I haven't seen `xcconfig` used within a subspec before.

**Comment by jhersh** [comment]
I've been reconsidering this as of late. This entire mess, and its workaround, applies only to people who (1) use `TTTAttributedLabel` as a static library and (2) attempt to configure a label in IB. I have to imagine that's a vanishingly small section of the userbase, and this workaround is awfully invasive for such a minority use case. There are other, much more stable workarounds, like using a dynamic framework.

I think it might be simpler and cleaner to instead document this limitation and leave it there.

**Pull request closed without merging**
