### PR TITLE
Add framework target compatible with Carthage

### PR DESCRIPTION
**Pull request by wtmoose**
The example project is linked to the source files through Cocoapods, so a new project needs to be added for creating the framework. This has been tested with Carthage.

The basic steps are as follows:
1. Create a Cocoa Touch Framework project
2. Add TTAttributedLabel source files to the project
3. Add `TTTAttributedLabelVersionNumber` and `TTTAttributedLabelVersionString[]` to the header file
3. Set target's scheme to "shared"
4. Add a Github label (same format as Cocoapods)

### CODE REVIEW

**Comment by jhersh** [comment]
Thanks @wtmoose! 

Must we necessarily have for Carthage (1) a new project (2) located in the repo root? Can we instead convert the sample `Espressos` project for use as all of (1) a sample project, (2) a Carthage framework project, and (3) the project's tests?

**Comment by wtmoose** [comment]
I’ll look into it tomorrow.

**Comment by wtmoose** [comment]
It looks like Carthage doesn't scan subdirectories for projects :(

I can think of a couple of improvements:

1. Move info.plist into a subdirectory (to reduce the number of top-level additions)
2. Merge the sample project and framework project and move to the top level (leaving all other files where they are)

**Comment by hankbao** [comment]
Please see my pr https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/532

**Comment by jhersh** [comment]
`TTTAttributedLabel` now supports Carthage via #532.

**Comment by wtmoose** [comment]
Thanks!

Tim

**Pull request closed without merging**
