### PR TITLE
Create TTTAttributedLabelLink class, and use it to manage default/active/inactive link state and accessibility values for non-default link types

### PR DESCRIPTION
**Pull request by getaaron**
- Create TTTAttributedLabelLink class, and use it to manage default/active/inactive link state and accessibility values for non-default link types
- Updates example project to compile properly with this new class
- Update documentation

### CODE REVIEW

**Comment by kylef** [comment]
@jhersh Anything blocking this PR from being merged?

@getaaron Would you be able to rebase this please.

**Comment by jhersh** [comment]
I would echo some of Mattt's comments above, in particular:

- Rebase on master please :top: 
- `TTTAttributedLabelLink` within `TTTAttributedLabel.{h,m}`
- Adding a text checking result should return the link object(s) created
- Link properties as public -- and `readonly` -- is a fine first step. Perhaps later we can look at informing the label of link property changes.

For bonus points:
- `NSCopying` for links
- Tests

**Comment by getaaron** [comment]
#### Done:

- [x] Rebase on master please :top:
- [x] TTTAttributedLabelLink within TTTAttributedLabel.{h,m}
- [x] Adding a text checking result should return the link object(s) created
- [x] NSCopying for links

#### Not Done:

- [ ] Link properties as public -- and `readonly`

Marking link properties as `readonly` will make it impossible to do this:

```objc
TTTAttributedLabelLink *newLink = [[TTTAttributedLabelLink alloc] init];
newLink.result = // some result…
newLink.activeAttributes = // some attributes…
[label addLink:newLink];
```

So I didn't move forward with that for now. We could add a custom initializer (`initWithResult:attributes:activeAttributes:inactiveAttributes:`) with `readonly` properties, but that will look pretty ugly in practice.

- [ ] Tests

No tests… yet.

**Comment by getaaron** [comment]
@kylef @jhersh I added you as collaborators on my fork if you want to make any changes. I probably won't be able to get back to this until the weekend.

**Comment by jhersh** [comment]
> (initWithResult:attributes:activeAttributes:inactiveAttributes:) with readonly properties, but that will look pretty ugly in practice.

I'm okay with that. We're gonna need a bigger initializer :boat:

> As it's written now, the link is initially assigned the label's three attribute dictionaries, overwriting attributes if the developer passed one in

Wasn't this one of @kylef's concerns in the first place? It'd be good to try and square this one away.

**Comment by getaaron** [comment]
> Wasn't this one of @kylef's concerns in the first place? It'd be good to try and square this one away.

Yes, but without any changes he can work around it now. What should the expected behavior of `addLinkWithTextCheckingResult:attributes:` be given the related changes in this PR?

- Should `activeAttributes` and `inactiveAttributes` be generated somehow, or should they be copied from the label?
- Should the method be updated to require the developer to pass in all three?
- Should we just deprecate `addLinkWithTextCheckingResult:attributes:` since this functionality can be more simply accomplished by passing a customized link object to `addLink:`?

**Comment by kylef** [comment]
@getaaron Quoting the docs, nothing should happen if the attributes there are nil.

> The attributes to be added to the text in the range of the specified link. If nil, no attributes are added.

So according to that, I think it should create a link with no active, inactive attributes

**Comment by getaaron** [comment]
@kylef Just pushed some changes. I tried to minimally change the behavior of `addLinkWithTextCheckingResult:attributes:` and I documented the new expected behavior. Can you please test my fork against your app and see if it resolves your issue?

**Comment by getaaron** [comment]
@jhersh Added a little test coverage, including two tests that cover @kylef's issue. Please let me know if there are additional tests you can think of.

**Comment by jhersh** [comment]
Thanks @getaaron! Would you consider squashing your commits, rebasing, and removing your deletion of the `.xcworkspace`? It should probably be removed all the same, but that's not related to this pull.

**Comment by getaaron** [comment]
@jhersh Done.

**Comment by jhersh** [comment]
I updated some docs and did some minor cleanup. Thanks for this @getaaron!

**Comment by kylef** [comment]
Nick work, thanks for getting this in @jhersh @getaaron :+1: :beers:.

**Pull request merged**
