### PR TITLE
Remove iOS 9 warning. 

### PR DESCRIPTION
**Pull request by KILLI**
NSLinkAttributeName address is always true in OS 7 and higher

### CODE REVIEW

**Comment by jhersh** [comment]
This will crash apps compiled with the iOS 9 SDK running on iOS 6 or older devices.

**Comment by KILLI** [comment]
Sure…
Could we hide a warning under suppress warnings declaration?

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Waddress"

**Comment by sirnacnud** [comment]
Correct me if I am wrong, but wouldn't a better fix be to add a runtime check for iOS 7 and remove checking if `NSLinkAttributeName` exists?

    if (NSFoundationVersionNumber > NSFoundationVersionNumber_iOS_6_1) {
        [self.attributedText enumerateAttribute:NSLinkAttributeName...];
    }

**Comment by sibljon** [comment]
Hi there!

Is there any way we can get this pull request merged?

If it were up to me, I'd move the `#pragma clang diagnostic pop` line up a few lines to directly beneath the  `if (&NSLinkAttributeName) {` line, so:

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Waddress"
    if (&NSLinkAttributeName) {
#pragma clang diagnostic pop
```

**Pull request closed without merging**
