### PR TITLE
[Circle] Use Xcode 7.3

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
Ok, had to rebuild the specs and bump dependencies but this is now passing! \m/
I guess I'll ship an update tomorrow with these changes?

**Comment by segiddins** [comment]
Consensus on https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/586 seems to be to bump to 8.0+ -- @jessesquires that change cool with you?

**Comment by jessesquires** [comment]
@segiddins 👍 sounds good to me!

btw, really happy to see you on this project now! 😊 

unfortunately, i haven't been able to contribute much, but hopefully that'll change soon!

**Comment by jessesquires** [comment]
this will be release 2.0, then correct?

**Comment by segiddins** [comment]
Sure ;)

**Comment by segiddins** [comment]
I have no idea why codecov isn't reporting the updated status :/

**Comment by jessesquires** [comment]
Looks like status is currently ok (http://status.codecov.io/)

However, codecov has been very uncooperative lately with many of my other projects. 😒

**Comment by segiddins** [comment]
@jessesquires you OK with me bumping the iOS version and merging even with that yellow?

**Comment by jessesquires** [comment]
@segiddins 👍

**Pull request merged**
