### PR TITLE
ITMS-90809: Deprecated API Usage (UIWebView)

### PR DESCRIPTION
**Pull request by svetlanama**

### CODE REVIEW

**Review by DarkSatyr — APPROVED** [review]

**Review by neljaj — APPROVED** [review]

**Review by rorybeling — APPROVED** [review]
Apple picking this up as an issue and blocking builds.

**Review by ruby109 — APPROVED** [review]

**Review by jrtaal — APPROVED** [review]

**Review by StefanICT — APPROVED** [review]

**Review by mahmut-codeway — APPROVED** [review]

**Review by jzeferino — APPROVED** [review]

**Review by MirzaBasic — APPROVED** [review]

**Review by jolyot — APPROVED** [review]

**Review by ctr119 — APPROVED** [review]

**Comment by jzeferino** [comment]
@segiddins can you please take a look at this. this is very important.

**Comment by segiddins** [comment]
All this PR is doing is changing a comment, I don’t think it’s addressing the underlying API usage that iTunes Connect is complaining about

**Comment by jzeferino** [comment]
@segiddins I know its weird but for a lot of people apps are being rejected due to this library, and the only reference to `UIWebView` is in the comments so I'm assuming Apple is looking at the source of this library and searching for `UIWebView`.
Do you mind to do that release so we can test if this is the issue?

**Comment by segiddins** [comment]
Has someone submitted with this patch applied and confirmed it fixes the issue?

**Review by Gabriel-Azevedo — APPROVED** [review]

**Comment by Gabriel-Azevedo** [comment]
@segiddins I just submitted to Testflight pointing to the `svetlanama:issue-810` branch and it worked.

**Comment by svetlanama** [comment]
> @segiddins I just submitted to Testflight pointing to the `svetlanama:issue-810` branch and it worked.

It helped to me also
I use `grep` to check all things before uploading to AppStore
```
cd app
grep -r "UIWebView" .
./Pods/TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.h: to emulate the link detection behaviour of UIWebView.
```

After applying changes  `svetlanama:issue-810`  it was gone. 
The processing of the build was completed successful without issues.

**Comment by jzeferino** [comment]
@segiddins when you plan to release this?

**Comment by Kaloian92** [comment]
Same question as jzeferino, when do you plan do release this, because all of the apps that are using "TTTAttributedLabel" should use this fix, if they want to release their app in the AppStore?

**Comment by Kaloian92** [comment]
Hi again, sorry for the spam, but we still need to know if you are planing to release this or not, as it is now mandatory for any project that use "TTTAttributedLabel", to use svetlanama's fix

**Pull request merged**
